// Generated by scripts/run.py. Numbers match metrics.json. Do not hand-edit.

export const ILLUSTRATIVE = false

export const PROTOCOL = {
  nClasses: 10,
  nTrain: 1000,
  nTest: 200,
  steps: 80,
  width: 24,
  img: 28,
  nRot: 8,
  angles: [0, 45, 90, 135, 180, 225, 270, 315],
}

export const METRICS = {
  successPct: 92.0,
  cnnRotatedPct: 32.5,
  uprightPct: 95.5,
  cnnUprightPct: 95.5,
  cnnAugRotatedPct: 28.0,
  chancePct: 10.0,
}

export type FamilyRow = {
  family: string
  attach: string
  group: string
  paramsTotal: number
  uprightPct: number
  rotatedPct: number
  aug: boolean
}

export const FAMILIES: FamilyRow[] = [
  {
    "family": "cnn",
    "attach": "plain_conv",
    "group": "none",
    "paramsTotal": 31930,
    "uprightPct": 95.5,
    "rotatedPct": 32.5,
    "aug": false
  },
  {
    "family": "equivariant",
    "attach": "orientation_pool",
    "group": "C8",
    "paramsTotal": 31930,
    "uprightPct": 95.5,
    "rotatedPct": 92.0,
    "aug": false
  },
  {
    "family": "cnn_aug",
    "attach": "plain_conv",
    "group": "none",
    "paramsTotal": 31930,
    "uprightPct": 19.5,
    "rotatedPct": 28.0,
    "aug": true
  }
]
